server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/wms2?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  type-aliases-package: com.eshore.wms.sys.entity
  #xml自动刷新，无需重启项目，该配置不建议在生产环境打开！
  global-config:
    refresh: true
